services:
  homeassistant:
    container_name: morningsideheights
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "127.0.0.1:8123:8123"
    volumes:
      - ./morningsideheights:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    # network_mode: host
